# Use new container infrastructure to enable caching
sudo: false


# Generic language, we provide our custom builds
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.local
  - $HOME/.ghc

# Only clone the repo's tip
git:
  depth: false

# Setup some global env variables
env:
  global:
  - PATH=$HOME/.local/bin:$PATH

# Define custom set of stages
stages:
- wallet-new-specs
- hlint

# Build snapshot & dependencies in different jobs. This copes with Travis limit of 50 minutes per job.
jobs:
  include:
  - stage: wallet-new-specs
    script:
    - mkdir -p ~/.local/bin
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack --no-terminal test --coverage
    after_script:
    - cabal install codecov-haskell
    - codecov-haskell test-test

  - stage: hlint
    script:
      - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s . --cpp-define=__GLASGOW_HASKELL__=800 --cpp-define=x86_64_HOST_ARCH=1 --cpp-define=mingw32_HOST_OS=1

