# Use new container infrastructure to enable caching
sudo: false

# Generic language, we provide our custom builds
language: generic

# Caching so the next build will be fast too.
cache:
  timeout: 1337
  directories:
  - $HOME/.stack
  - $HOME/.local
  - $HOME/.ghc
  - $HOME/Library/Caches/Homebrew
  - $TRAVIS_BUILD_DIR/.stack-work

# Only clone the repo's tip
git:
  depth: false

# Setup some global env variables
env:
  global:
  - PATH=$HOME/.local/bin:$PATH

# Define custom set of stages
stages:
- snapshot

# Build snapshot & dependencies in different jobs. This copes with Travis limit of 50 minutes per job.
jobs:
  include:
  - stage: snapshot
    if: commit_message =~ /Bump LTS/
    script:
    - mkdir -p ~/.local/bin
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - travis_wait 42 stack --no-terminal --install-ghc build --only-snapshot
    - stack --no-terminal install cpphs
    - brew install rocksdb
    - travis_wait 42 stack --no-terminal test cardano-sl-wallet-new:test:wallet-new-specs --ghc-options=-optl-Wl,-dead_strip_dylibs --coverage
    after_script:
    - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
    - ./shc test wallet-new-specs
