# Use new container infrastructure to enable caching
sudo: false

# Use OSX to by-pass issue with CouchDB PGP Key on Linux
os: osx

# Generic language, we provide our custom builds
language: generic

# Caching so the next build will be fast too.
cache:
  timeout: 1337
  directories:
  - $HOME/.stack
  - $HOME/.local
  - $HOME/.ghc
  - $TRAVIS_BUILD_DIR/.stack-work

# Only clone the repo's tip
git:
  depth: false

# Setup some global env variables
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - HOMEBREW_NO_AUTO_UPDATE=1
  - HOMEBREW_CACHE=$HOME/.local/Homebrew

# Define custom set of stages
stages:
- snapshot
- extra-dependencies
- wallet-new-specs

# Install rocksdb DLL
before_install:
- brew install rocksdb

# Build snapshot & dependencies in different jobs. This copes with Travis limit of 50 minutes per job.
jobs:
  include:
  - stage: snapshot
    if: commit_message =~ /Bump LTS/
    script:
    - mkdir -p ~/.local/bin
    - travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    - travis_wait 42 stack --no-terminal --install-ghc build --only-snapshot
    - stack --no-terminal install cpphs

  - stage: extra-dependencies
    if: commit_message =~ /Update stack.yaml/
    script:
    - travis_wait 42 stack --no-terminal build --fast --only-dependencies

  - stage: wallet-new-specs
    script:
    - stack clean
    - travis_wait 42 stack --no-terminal test cardano-sl-wallet-new:test:wallet-new-specs
    - stack clean
