# Use new container infrastructure to enable caching
sudo: false

# Use OSX to by-pass issue with CouchDB PGP Key on Linux
os: osx

# Generic language, we provide our custom builds
language: generic

# Caching so the next build will be fast too.
cache:
  timeout: 1337
  directories:
  - $HOME/.stack
  - $HOME/.local
  - $HOME/.ghc
  - $HOME/Library/Caches/Homebrew
  - $TRAVIS_BUILD_DIR/.stack-work

# Only clone the repo's tip
git:
  depth: false

# Setup some global env variables
env:
  global:
  - PATH=$HOME/.local/bin:$PATH

# Define custom set of stages
stages:
- snapshot
- extra-dependencies
- cardano-sl
- wallet-new-specs

# Build snapshot & dependencies in different jobs. This copes with Travis limit of 50 minutes per job.
jobs:
  include:
  - stage: snapshot
    if: commit_message =~ /Bump LTS/
    script:
    - mkdir -p ~/.local/bin
    - travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    - travis_wait 42 stack --no-terminal --install-ghc build --only-snapshot
    - stack --no-terminal install cpphs

  - stage: extra-dependencies
    if: commit_message =~ /Update stack.yaml/
    script:
    - brew install rocksdb
    - travis_wait 42 stack --no-terminal build --fast plutus-prototype cardano-report-server cardano-crypto ip cborg time-units kademlia network-transport network-transport-tcp network-transport-inmemory acid-state canonical-json clock rocksdb-haskell-ng log-warper hedgehog servant-quickcheck universum serokell-util

  - stage: cardano-sl
    if: commit_message =~ /Update stack.yaml/
    script:
    - brew install rocksdb
    - travis_wait 42 stack --no-terminal build --fast cardano-sl

  - stage: wallet-new-specs
    script:
    - brew install rocksdb
    - stack clean
    - travis_wait 42 stack --no-terminal test cardano-sl-wallet-new:test:wallet-new-specs --ghc-options=-optl-Wl,-dead_strip_dylibs
    after_script:
    - travis_retry wget https://gist.github.com/Anviking/323c184cbb7d16e1d9eed852dd58714c/raw/a895eb8380eaa0a6f83dd5d09f4aff2e066f46e9/shc
    - ./shc test wallet-new-specs
