version: 2




jobs:
  build_project:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - run: echo “Hello”
      - run: echo $COVERALLS_REPO_TOKEN
      - run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev -y
      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-1.7.1-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-1.7.1-linux-x86_64/stack /usr/bin/stack
      - run: stack test --coverage

        # Coveralls
      - run: curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
      - run: ./shc cardano-sl-wallet-new wallet-new-specs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
