version: 2




jobs:
  build_project:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - run: echo “Hello”
      - run: echo $COVERALLS_REPO_TOKEN
      - run: nix-channel --add https://nixos.org/channels/nixos-unstable nixos
      - run: nix-channel --add https://nixos.org/channels/nixos-18.09
      - run: nix-channel --update
      - run: |
          nix-env -f "<nixpkgs>" -iA haskellPackages.cpphs stack haskell.compiler.ghc822 rocksdb
      - run: stack test --coverage

        # Coveralls
      - run: curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
      - run: ./shc cardano-sl-wallet-new wallet-new-specs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
