version: 2




jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - restore_cache:
          keys:
            - stackyaml-{{ checksum "stack.yaml" }}
            - stackyaml-checksum-failed

      - run: echo $PATH


      - run: apt-get update && apt-get install -y librocksdb-dev

      # for stack
      - run: apt-get install -y curl netbase xz-utils make liblzma-dev

      # https://discuss.circleci.com/t/non-deterministic-cache-restore-behaviour/16291/10
      - run: apt-get install -y ca-certificates


        #      - run: git clone https://github.com/facebook/rocksdb.git
        #- run: cd rocksdb; DEBUG_LEVEL=0 sudo make shared_lib install-shared

      - run: curl -sSL https://get.haskellstack.org/ | sh
      - run: stack --no-terminal --install-ghc build --only-snapshot

      - save_cache:
          key: stackyaml-{{ checksum "stack.yaml" }}
          paths:
            - $HOME/.stack

      - run: stack test --coverage

        # Coveralls
      - run: curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
      - run: ./shc cardano-sl-wallet-new wallet-new-specs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
