version: 2
jobs:
  build_project:
    machine: true
    steps:
      - checkout
      - run: echo “Hello”
      - run: echo $COVERALLS_REPO_TOKEN
      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-1.7.1-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-1.7.1-linux-x86_64/stack /usr/bin/stack
      - run: stack test --coverage
      - run: git clone https://github.com/nirum-lang/codecov-haskell.git; cd codecov-haskell
      - run: git checkout 8448801f8d01624e4cd60420beb3fdc85c099576
      - run: stack install; cd ..
      - run: codecov-haskell test-test
      - run: curl -L https://github.com/guillaume-nargeot/codecov-haskell/releases/download/v0.4.0.2/codecov-haskell-0.4.0.2.tar.gz | tar -xj
        #      - run: curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
        #- run: ./shc test test-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
